=== apache/incubator-marvin/engine-executor/src/test/resources/EngineMetadataSchema.json
{
  "$schema" : "http://json-schema.org/draft-04/schema" ,
  "id": "resource:/EngineMetadataSchema.json#",
  "title": "Metadata Schema",
  "description": "Schema for Engine Metadata validation",
  "type": "object",
  "properties": {
    "name": {
      "description": "Engine name",
      "type": "string"
    },
    "version": {
      "description": "Engine version",
      "type": "string"
    },
    "engineType": {
      "description": "Engine type",
      "type": "string"
    },
    "artifactsRemotePath": {
      "description": "Artifacts remote path",
      "type": "string"
    },
    "artifactManagerType": {
      "description": "Artifacts manager path",
      "type": "string"
    },
    "s3BucketName": {
      "description": "Amazon S3 bucket name",
      "type": "string"
    },
    "pipelineActions": {
      "description": "Pipeline actions",
      "type": "array",
      "items": {
        "type": "string"
      },
      "additionalItems": false
    },
    "onlineActionTimeout": {
      "type": "integer",
      "minimum": 1
    },
    "healthCheckTimeout": {
      "type": "integer",
      "minimum": 1
    },
    "reloadTimeout": {
      "type": "integer",
      "minimum": 1
    },
    "reloadStateTimeout": {
      "type": "integer",
      "minimum": 1
    },
    "batchActionTimeout": {
      "type": "integer",
      "minimum": 1
    },
    "hdfsHost": {
      "description": "HDFS host",
      "type": "string"
    },
    "actions": {
      "$ref": "EngineActionSchema.json#/actions"
    }
  },
  "required": ["name", "version", "engineType", "artifactsRemotePath", "artifactManagerType", "onlineActionTimeout", "healthCheckTimeout", "reloadTimeout", "batchActionTimeout", "pipelineActions", "actions"]
}

=== apache/incubator-marvin/engine-executor/src/test/resources/metadataToValidateWithRefError.json
{
  "name": "iris_species",
  "version": "v0.0.1",
  "engineType": "python",
  "artifactsRemotePath": "/tmp/marvin",
  "artifactManagerType": "s3",
  "s3BucketName": "marvin-artifact-bucket",
  "onlineActionTimeout": 1000,
  "healthCheckTimeout": 2000,
  "reloadTimeout": 600000,
  "batchActionTimeout": 600000,
  "hdfsHost": "hdfs://marvin-hadoop:8020",
  "pipelineActions": ["acquisitor", "tpreparator", "trainer", "evaluator"],
  "actions": [{
    "name": "acquisitor",
    "actionType": 123,
    "port": "aaa",
    "host": "localhost",
    "artifactsToPersist": ["initialdataset"],
    "artifactsToLoad": [],
    "pipeline": []
  }, {
    "name": "tpreparator",
    "actionType": "batch",
    "port": 50052,
    "host": "localhost",
    "artifactsToPersist": ["dataset"],
    "artifactsToLoad": ["initialdataset"],
    "pipeline": []
  }, {
    "name": "trainer",
    "actionType": "batch",
    "port": 50053,
    "host": "localhost",
    "artifactsToPersist": ["model"],
    "artifactsToLoad": ["dataset"],
    "pipeline": []
  }, {
    "name": "evaluator",
    "actionType": "batch",
    "port": 50054,
    "host": "localhost",
    "artifactsToPersist": ["metrics"],
    "artifactsToLoad": ["dataset", "model"],
    "pipeline": []
  }, {
    "name": "predictor",
    "actionType": "online",
    "port": 50055,
    "host": "localhost",
    "artifactsToPersist": [],
    "artifactsToLoad": ["model", "metrics"],
    "pipeline": ["ppreparator"]
  }]
}
